# Generated by Django 5.1.6 on 2025-10-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                ("mrp", models.IntegerField()),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
